package main

import (
	"fmt"
	"os"
	"strings"
)

// generateSQL produces a complete PostgreSQL DDL string from the given state.
func generateSQL(state *AppState) string {
	var b strings.Builder

	b.WriteString("-- Generated by Schemata\n\n")

	// CREATE SCHEMA statements
	for _, s := range state.Schemas {
		b.WriteString(fmt.Sprintf("CREATE SCHEMA IF NOT EXISTS %s;\n", quoteIdent(s.Name)))
	}
	if len(state.Schemas) > 0 {
		b.WriteString("\n")
	}

	// CREATE TYPE statements for enums
	for _, e := range state.EnumTypes {
		vals := make([]string, len(e.Values))
		for i, v := range e.Values {
			vals[i] = fmt.Sprintf("'%s'", strings.ReplaceAll(v, "'", "''"))
		}
		b.WriteString(fmt.Sprintf("CREATE TYPE %s.%s AS ENUM (%s);\n", quoteIdent(e.Schema), quoteIdent(e.Name), strings.Join(vals, ", ")))
	}
	if len(state.EnumTypes) > 0 {
		b.WriteString("\n")
	}

	// CREATE TABLE statements
	for _, t := range state.Tables {
		b.WriteString(fmt.Sprintf("CREATE TABLE %s.%s (\n", quoteIdent(t.Schema), quoteIdent(t.Name)))

		var colDefs []string
		var pkCols []string

		// Check if there is a table-level PK constraint
		hasTablePK := false
		for _, tc := range t.Constraints {
			if tc.Type == "primary_key" {
				hasTablePK = true
				break
			}
		}

		for _, c := range t.Columns {
			def := fmt.Sprintf("    %s %s", quoteIdent(c.Name), c.Type)
			if !c.Nullable {
				def += " NOT NULL"
			}
			if c.Unique {
				def += " UNIQUE"
			}
			if c.Default != "" {
				def += " DEFAULT " + c.Default
			}
			colDefs = append(colDefs, def)
			if c.PrimaryKey && !hasTablePK {
				pkCols = append(pkCols, quoteIdent(c.Name))
			}
		}

		if len(pkCols) > 0 {
			colDefs = append(colDefs, fmt.Sprintf("    PRIMARY KEY (%s)", strings.Join(pkCols, ", ")))
		}

		// Table-level constraints
		for _, tc := range t.Constraints {
			quotedCols := make([]string, len(tc.Columns))
			for i, col := range tc.Columns {
				quotedCols[i] = quoteIdent(col)
			}
			switch tc.Type {
			case "primary_key":
				constraintName := fmt.Sprintf("%s_pkey", t.Name)
				colDefs = append(colDefs, fmt.Sprintf("    CONSTRAINT %s PRIMARY KEY (%s)", quoteIdent(constraintName), strings.Join(quotedCols, ", ")))
			case "unique":
				constraintName := fmt.Sprintf("%s_%s_unique", t.Name, strings.Join(tc.Columns, "_"))
				colDefs = append(colDefs, fmt.Sprintf("    CONSTRAINT %s UNIQUE (%s)", quoteIdent(constraintName), strings.Join(quotedCols, ", ")))
			case "check":
				colDefs = append(colDefs, fmt.Sprintf("    CONSTRAINT %s CHECK (%s)", quoteIdent(tc.Name), tc.Expression))
			}
		}

		b.WriteString(strings.Join(colDefs, ",\n"))
		b.WriteString("\n);\n\n")
	}

	// ALTER TABLE ADD CONSTRAINT for foreign keys
	for _, fk := range state.ForeignKeys {
		constraintName := fmt.Sprintf("%s_%s_foreign", fk.FromTable, fk.FromColumn)
		fkSQL := fmt.Sprintf(
			"ALTER TABLE %s.%s ADD CONSTRAINT %s FOREIGN KEY (%s) REFERENCES %s.%s (%s)",
			quoteIdent(fk.FromSchema), quoteIdent(fk.FromTable),
			quoteIdent(constraintName),
			quoteIdent(fk.FromColumn),
			quoteIdent(fk.ToSchema), quoteIdent(fk.ToTable),
			quoteIdent(fk.ToColumn),
		)
		if fk.OnDelete != "" {
			fkSQL += " ON DELETE " + fk.OnDelete
		}
		if fk.OnUpdate != "" {
			fkSQL += " ON UPDATE " + fk.OnUpdate
		}
		b.WriteString(fkSQL + ";\n")
	}

	// Column comments
	for _, t := range state.Tables {
		for _, c := range t.Columns {
			if c.Comment != "" {
				b.WriteString(fmt.Sprintf("COMMENT ON COLUMN %s.%s.%s IS '%s';\n",
					quoteIdent(t.Schema), quoteIdent(t.Name), quoteIdent(c.Name),
					strings.ReplaceAll(c.Comment, "'", "''")))
			}
		}
	}

	// Indexes
	for _, t := range state.Tables {
		for _, idx := range t.Indexes {
			quotedCols := make([]string, len(idx.Columns))
			for i, col := range idx.Columns {
				quotedCols[i] = quoteIdent(col)
			}
			if idx.Unique {
				b.WriteString(fmt.Sprintf("CREATE UNIQUE INDEX %s ON %s.%s (%s);\n",
					quoteIdent(idx.Name), quoteIdent(t.Schema), quoteIdent(t.Name), strings.Join(quotedCols, ", ")))
			} else {
				b.WriteString(fmt.Sprintf("CREATE INDEX %s ON %s.%s (%s);\n",
					quoteIdent(idx.Name), quoteIdent(t.Schema), quoteIdent(t.Name), strings.Join(quotedCols, ", ")))
			}
		}
	}

	// Views
	if len(state.Views) > 0 {
		b.WriteString("\n")
		for _, v := range state.Views {
			// Build SELECT from columns with source references
			var selectCols []string
			var fromTables []string
			fromSet := make(map[string]bool)

			for _, vc := range v.Columns {
				if vc.SourceSchema != "" && vc.SourceTable != "" && vc.SourceColumn != "" {
					alias := vc.SourceTable
					selectCols = append(selectCols, fmt.Sprintf("%s.%s AS %s",
						quoteIdent(alias), quoteIdent(vc.SourceColumn), quoteIdent(vc.Name)))
					fromKey := fmt.Sprintf("%s.%s", vc.SourceSchema, vc.SourceTable)
					if !fromSet[fromKey] {
						fromSet[fromKey] = true
						fromTables = append(fromTables, fmt.Sprintf("%s.%s %s",
							quoteIdent(vc.SourceSchema), quoteIdent(vc.SourceTable), quoteIdent(alias)))
					}
				} else {
					selectCols = append(selectCols, quoteIdent(vc.Name))
				}
			}

			if len(selectCols) == 0 {
				selectCols = append(selectCols, "*")
			}

			b.WriteString(fmt.Sprintf("CREATE OR REPLACE VIEW %s.%s AS\n  SELECT %s",
				quoteIdent(v.Schema), quoteIdent(v.Name),
				strings.Join(selectCols, ",\n         ")))

			if len(fromTables) > 0 {
				b.WriteString(fmt.Sprintf("\n  FROM %s", strings.Join(fromTables, ",\n       ")))
			}
			b.WriteString(";\n\n")

			if v.Comment != "" {
				b.WriteString(fmt.Sprintf("COMMENT ON VIEW %s.%s IS '%s';\n",
					quoteIdent(v.Schema), quoteIdent(v.Name),
					strings.ReplaceAll(v.Comment, "'", "''")))
			}
		}
	}

	return b.String()
}

// quoteIdent wraps an identifier in double quotes for PostgreSQL.
func quoteIdent(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `""`) + `"`
}

// writeFile writes content to the given path.
func writeFile(path, content string) error {
	return os.WriteFile(path, []byte(content), 0644)
}
