// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCheck(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function AddColumn(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean,arg6:boolean,arg7:boolean,arg8:string,arg9:string,arg10:number,arg11:string):Promise<void>;

export function AddConstraint(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function AddExtension(arg1:string):Promise<void>;

export function AddForeignKey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:string):Promise<void>;

export function AddIndex(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:boolean,arg6:string,arg7:string):Promise<void>;

export function Clear():Promise<void>;

export function ClearTablePosition(arg1:string,arg2:string):Promise<void>;

export function ClearViewPosition(arg1:string,arg2:string):Promise<void>;

export function CreateEnum(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function CreateSchema(arg1:string,arg2:string):Promise<void>;

export function CreateTable(arg1:string,arg2:string):Promise<void>;

export function CreateView(arg1:string,arg2:string,arg3:Array<main.ViewColumn>):Promise<void>;

export function DeleteCheck(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteColumn(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteConstraint(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<void>;

export function DeleteEnum(arg1:string,arg2:string):Promise<void>;

export function DeleteExtension(arg1:string):Promise<void>;

export function DeleteForeignKey(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteIndex(arg1:string,arg2:string,arg3:string):Promise<void>;

export function DeleteSchema(arg1:string):Promise<void>;

export function DeleteTable(arg1:string,arg2:string):Promise<void>;

export function DeleteView(arg1:string,arg2:string):Promise<void>;

export function ExportSQL():Promise<string>;

export function GetCurrentFile():Promise<string>;

export function GetMCPPath():Promise<string>;

export function GetState():Promise<main.AppState>;

export function GetStateJSON():Promise<string>;

export function LoadProject(arg1:string):Promise<void>;

export function OpenProjectDialog():Promise<string>;

export function Redo():Promise<void>;

export function RenameTable(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ReorderColumns(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function SaveProject(arg1:string):Promise<void>;

export function SaveProjectDialog():Promise<string>;

export function SaveSQL():Promise<string>;

export function SetTablePosition(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function SetViewPosition(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function Undo():Promise<void>;

export function UpdateColumn(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function UpdateConstraint(arg1:string,arg2:string,arg3:string,arg4:Array<string>,arg5:Array<string>):Promise<void>;

export function UpdateEnum(arg1:string,arg2:string,arg3:Array<string>):Promise<void>;

export function UpdateForeignKey(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function UpdateIndex(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<void>;

export function UpdateSchema(arg1:string,arg2:Record<string, any>):Promise<void>;

export function UpdateTable(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;

export function UpdateView(arg1:string,arg2:string,arg3:Record<string, any>):Promise<void>;
