// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCheck(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCheck'](arg1, arg2, arg3, arg4);
}

export function AddColumn(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11) {
  return window['go']['main']['App']['AddColumn'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);
}

export function AddConstraint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddConstraint'](arg1, arg2, arg3, arg4);
}

export function AddExtension(arg1) {
  return window['go']['main']['App']['AddExtension'](arg1);
}

export function AddForeignKey(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['AddForeignKey'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function AddIndex(arg1, arg2, arg3, arg4, arg5, arg6, arg7) {
  return window['go']['main']['App']['AddIndex'](arg1, arg2, arg3, arg4, arg5, arg6, arg7);
}

export function Clear() {
  return window['go']['main']['App']['Clear']();
}

export function ClearTablePosition(arg1, arg2) {
  return window['go']['main']['App']['ClearTablePosition'](arg1, arg2);
}

export function ClearViewPosition(arg1, arg2) {
  return window['go']['main']['App']['ClearViewPosition'](arg1, arg2);
}

export function CreateEnum(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateEnum'](arg1, arg2, arg3);
}

export function CreateSchema(arg1, arg2) {
  return window['go']['main']['App']['CreateSchema'](arg1, arg2);
}

export function CreateTable(arg1, arg2) {
  return window['go']['main']['App']['CreateTable'](arg1, arg2);
}

export function CreateView(arg1, arg2, arg3) {
  return window['go']['main']['App']['CreateView'](arg1, arg2, arg3);
}

export function DeleteCheck(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteCheck'](arg1, arg2, arg3);
}

export function DeleteColumn(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteColumn'](arg1, arg2, arg3);
}

export function DeleteConstraint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteConstraint'](arg1, arg2, arg3, arg4);
}

export function DeleteEnum(arg1, arg2) {
  return window['go']['main']['App']['DeleteEnum'](arg1, arg2);
}

export function DeleteExtension(arg1) {
  return window['go']['main']['App']['DeleteExtension'](arg1);
}

export function DeleteForeignKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteForeignKey'](arg1, arg2, arg3);
}

export function DeleteIndex(arg1, arg2, arg3) {
  return window['go']['main']['App']['DeleteIndex'](arg1, arg2, arg3);
}

export function DeleteSchema(arg1) {
  return window['go']['main']['App']['DeleteSchema'](arg1);
}

export function DeleteTable(arg1, arg2) {
  return window['go']['main']['App']['DeleteTable'](arg1, arg2);
}

export function DeleteView(arg1, arg2) {
  return window['go']['main']['App']['DeleteView'](arg1, arg2);
}

export function ExportSQL() {
  return window['go']['main']['App']['ExportSQL']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetMCPPath() {
  return window['go']['main']['App']['GetMCPPath']();
}

export function GetState() {
  return window['go']['main']['App']['GetState']();
}

export function GetStateJSON() {
  return window['go']['main']['App']['GetStateJSON']();
}

export function LoadProject(arg1) {
  return window['go']['main']['App']['LoadProject'](arg1);
}

export function OpenProjectDialog() {
  return window['go']['main']['App']['OpenProjectDialog']();
}

export function Redo() {
  return window['go']['main']['App']['Redo']();
}

export function RenameTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenameTable'](arg1, arg2, arg3);
}

export function ReorderColumns(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReorderColumns'](arg1, arg2, arg3);
}

export function SaveProject(arg1) {
  return window['go']['main']['App']['SaveProject'](arg1);
}

export function SaveProjectDialog() {
  return window['go']['main']['App']['SaveProjectDialog']();
}

export function SaveSQL() {
  return window['go']['main']['App']['SaveSQL']();
}

export function SetTablePosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetTablePosition'](arg1, arg2, arg3, arg4);
}

export function SetViewPosition(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetViewPosition'](arg1, arg2, arg3, arg4);
}

export function Undo() {
  return window['go']['main']['App']['Undo']();
}

export function UpdateColumn(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateColumn'](arg1, arg2, arg3, arg4);
}

export function UpdateConstraint(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['UpdateConstraint'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateEnum(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateEnum'](arg1, arg2, arg3);
}

export function UpdateForeignKey(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateForeignKey'](arg1, arg2, arg3, arg4);
}

export function UpdateIndex(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateIndex'](arg1, arg2, arg3, arg4);
}

export function UpdateSchema(arg1, arg2) {
  return window['go']['main']['App']['UpdateSchema'](arg1, arg2);
}

export function UpdateTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateTable'](arg1, arg2, arg3);
}

export function UpdateView(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateView'](arg1, arg2, arg3);
}
